language: ruby

services:
  - docker
  
script:
  - cd image && docker build -t jtschichold/minemeld:$TRAVIS_BRANCH .

after_success:
  - docker images

deploy:
  provider: script
  script: chmod +x ./scripts/deploy-image.sh && ./scripts/deploy-image.sh
  on:
    branch: develop
