language: ruby

services:
  - docker
  
script:
  - cd image && docker build -t jtschichold/minemeld:$TRAVIS_BRANCH .

after_success:
  - docker images

deploy:
  provider: script
  script: chmod +x $TRAVIS_BUILD_DIR/scripts/deploy-image.sh && $TRAVIS_BUILD_DIR/scripts/deploy-image.sh
  on:
    all_branches: true
